apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: fact-or-fake-game
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: postgres
        image: registry.gitlab.com/tduchnowski1/fact-or-fake-game/postgres:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "FactOrFake"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "FactOrFakeDb"
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "pg_isready -U postgres"
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "pg_isready -U postgres"
          initialDelaySeconds: 30
          periodSeconds: 30
