apiVersion: v1
kind: Service
metadata:
  name: game-server
  namespace: fact-or-fake-game 
spec:
  selector:
    app: game-server
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
  sessionAffinity: ClientIP
