apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server
  namespace: fact-or-fake-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: game-server
        image: registry.gitlab.com/tduchnowski1/fact-or-fake-game/truefalsebackend:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__Redis
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: ConnectionStrings__Redis
        - name: ConnectionStrings__Postgres
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: ConnectionStrings__Postgres
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
