apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  namespace: fact-or-fake-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bot
        image: registry.gitlab.com/tduchnowski1/fact-or-fake-game/fact-or-fake-bot:1.0.0
        imagePullPolicy: Always
        env:
        - name: GAME_API_URL
          valueFrom:
            configMapKeyRef:
              name: bot-config
              key: GAME_API_URL
        - name: TG_API_URL
          valueFrom:
            configMapKeyRef:
              name: bot-config
              key: TG_API_URL
        - name: BOT_TOKEN
          valueFrom:
            configMapKeyRef:
              name: bot-config
              key: BOT_TOKEN
        - name: MINI_APP_DIRECT_LINK
          valueFrom:
            configMapKeyRef:
              name: bot-config
              key: MINI_APP_DIRECT_LINK
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: bot-config
              key: API_KEY
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
